install <- function(pkg) {
    install.packages(pkg, repos="https://cloud.r-project.org")
}

install("Rcpp")
install("BH")
install("data.table")
install("plyr")
install("dplyr")
install("dtplyr")
install("ggplot2")
install("gridExtra")
install("foreach")
install("parallel")
install("doParallel")
install("stringr")
install("lubridate")
install("TimeWarp")
install("Holidays")
install("RODBC")
install("zoo")
install("xts")
install("devtools")
install("testthat")
install("roxygen2")
install("Quandl")
install("fst")
install("devtools")

